apiVersion: apps/v1
kind: Deployment
metadata:
  name: justcrashme
  labels:
    category: pwn
    challenge: justcrashme
spec:
  replicas: 2
  selector:
    matchLabels:
      category: pwn
      challenge: justcrashme
  template:
    metadata:
      labels:
        category: pwn
        challenge: justcrashme
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/justcrashme
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 8000
          name: tcp
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 3
          periodSeconds: 30